name: Build Windows .exe

on:
  push:
    branches:
      - main  # ganti sesuai branch trigger-mu

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        # kalau pake pnpm, ganti run jadi:
        # run: pnpm install

      - name: Build Windows exe
        run: npx electron-packager . "CardPaymentMethod" --platform=win32 --arch=ia32 --overwrite --out=release-builds --icon=assets/icons/win/icon.ico

      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CardPaymentMethod-exe
          path: release-builds/**/*
